kind: Service
apiVersion: v1
metadata:
  name: api-pedidos
spec:
  selector:
    app: api-pedidos
  ports:
    - protocol: TCP
      port: 7071
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pedidos
spec:
  selector:
    matchLabels:
      app: api-pedidos
  replicas: 1
  template:
    metadata:
      labels:
        app: api-pedidos
    spec:
      containers:
        - name: api-pedidos
          image: api-pedidos
          imagePullPolicy: Never
          ports:
            - containerPort: 7071